name: Lint

on:
  pull_request:
    paths:
      - 'flash_attn/cute/flash_bwd_sm90.py'
      - 'flash_attn/cute/flash_bwd_preprocess.py'
      - 'flash_attn/cute/flash_bwd_postprocess.py'
      - 'flash_attn/cute/softmax.py'
      - '.pre-commit-config.yaml'
  push:
    branches:
      - main
    paths:
      - 'flash_attn/cute/flash_bwd_sm90.py'
      - 'flash_attn/cute/flash_bwd_preprocess.py'
      - 'flash_attn/cute/flash_bwd_postprocess.py'
      - 'flash_attn/cute/softmax.py'
      - '.pre-commit-config.yaml'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
